sudo: required

language: node_js

services: 
  - docker

before_install:
  - docker-compose build  # Build the Docker containers

script:
  - docker-compose up -d  # Start services in detached mode

env:
  - NODE_OPTIONS=--max_old_space_size=2048  # Limit Node.js memory usage

cache:
  directories:
    - node_modules  # Cache node_modules for faster builds


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'              # AWS region (step 1)
  app: 'docker'                    # Application Name in Elastic Beanstalk (step 2)
  env: 'docker-env'                # Beanstalk Environment Name in lowercase (step 3)
  bucket_name: 'elasticbeanstalk-us-east-2-061039788601' # S3 bucket name (step 4)
  bucket_path: 'docker'            # S3 bucket path (step 5)
  access_key_id: $AWS_ACCESS_KEY   # Access Key (step 6 - should be stored securely in Travis)
  secret_access_key: $AWS_SECRET_KEY # Secret Key (step 7 - should be stored securely in Travis)
  on:
    branch: main                   # Only deploy when changes are pushed to the main branch
