FROM node:22-alpine

# Set the working directory to /usr/app
WORKDIR /usr/app


#By structuring your Dockerfile first to copy package.json and package-lock.json, then running npm install before copying the rest of your application code, you take advantage of Docker’s caching mechanism. 

#This way, dependencies are only installed again if package.json changes. 
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .


CMD [ "npm" , "start"]